services:
  - type: web
    name: telegram-link-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false  # Значение задается вручную в Render Dashboard
      - key: PYTHON_VERSION
        value: 3.11.0  # Указываем версию Python, совместимую с вашим окружением
